- name: Install Suricata on all systems
  
  tasks:
    - name: Install Suricata on Windows 
      become: yes
      ansible.windows.win_shell: |
        Invoke-WebRequest -Uri 'https://npcap.com/dist/npcap-1.78.exe' -OutFile 'C:\Temp\npcap-1.78.exe' -UseBasicParsing
        Start-Process -FilePath 'C:\Temp\npcap-1.78.exe' -ArgumentList '/S' -Wait
        Invoke-WebRequest -Uri 'https://www.openinfosecfoundation.org/download/windows/Suricata-7.0.2-1-64bit.msi' -OutFile 'C:\Temp\Suricata-7.0.2-1.msi' -UseBasicParsing
        Start-Process -FilePath 'C:\Temp\Suricata-7.0.2-1.msi' -ArgumentList '/qn' -Wait
      args:
        executable: powershell.exe
      when: '"Windows" in ansible_system'

    - name: Get Suricata Configured and Running on Windows
      become: yes
      ansible.windows.win_shell: |
        $config_path = 'C:\Program Files\Suricata\suricata.yaml'
        Invoke-WebRequest -Uri 'https://rules.emergingthreats.net/open/suricata/emerging-all.rules' -OutFile 'C:\Program Files\Suricata\rules\emerging-all.rules' -UseBasicParsing
        Invoke-WebRequest -Uri 'https://github.com/maxgriff/AnsibleScripts/windows-suricata.yaml' -OutFile $config_path -UseBasicParsing
        $network = Get-NetIPInterface | Where-Object { $_.ConnectionState -eq 'Connected' -and $_.InterfaceAlias -notlike '*Loopback*' -and $_.AddressFamily -eq 'IPv4' } | Sort-Object -Property InterfaceMetric
        $interface_id = $network[0].InterfaceIndex
        $ip_addr = (Get-NetIPAddress -InterfaceIndex $interface_id | Where-Object {$_.AddressFamily -eq 'IPv4'}).IPAddress
        $config = Get-Content -Path $config_path
        $new_config = $config -replace '<IP-ADDRESS>', $ip_addr
        $new_config | Set-Content -Path $config_path
        cd $config_path
        .\Suricata.exe -c suricata.yaml -i $ip_addr --service-installi\
        start-service Suricata
      args:
        executable: powershell.exe
      when: '"Windows" in ansible_system'

    - name: Install Suricata on Linux
      block:
        - name: Install and Start Suricata on Ubuntu/Debian
          become: yes
          shell: |
            add-apt-repository -y ppa:oisf/suricata-stable
            apt install -y suricata
            systemctl enable suricata
            systemctl stop suricata
            curl "https://github.com/maxgriff/AnsibleScipts/linux-suricata.yaml" > /etc/suricata/suricata.yaml
            apt install -y jq
            inter=$(ip -p -j route show default | jq -r ".[0].dev")
            IP=$(ip -4 addr show $inter | awk '/inet /{print $2}' | cut -d't' -f2 | cut -d' ' -f2 | cut -d'/' -f1)
            CIDR=$(ip -4 addr show $inter | awk '/inet /{print $2}' | cut -d't' -f2 | cut -d' ' -f2 | cut -d'/' -f2)
            NETID=""
            if [ $CIDR -eq 8 ]; then
              NETID=$(echo $IP | cut -d'.' -f1)
              NETID=$NETID".0.0.0/8"
            fi
            if [ $CIDR -eq 16 ]; then
              NETID=$(echo $IP | cut -d'.' -f1-2)
              NETID=$NETID".0.0/16"
            fi
            if [ $CIDR -eq 24 ]; then
              NETID=$(echo $IP | cut -d'.' -f1-3)
              NETID=$NETID".0/24"
            fi
            if [ $NETID = "" ]; then
              NETID=$IP
            fi
            sed -i "s/<IP-ADDRESS>/$NETID/g" /etc/suricata/suricata.yaml
            sed -i "s/<INTERFACE>/$inter/g" /etc/suricata/suricata.yaml
            suricata-update
            systemctl start suricata
          when: ansible_os_family == 'Debian'

            

- name: Install Wazuh-Agent on All Systems Other Than Manager
  hosts: windows_hosts:linux_hosts
