- name: Install Suricata on Windows
  hosts: windows_hosts
  become: yes
  tags:
  - Windows
  tasks:
  - name: Install Suricata
    block:
    - name: Installing npcap
      ansible.windows.win_package:
        url: https://npcap.com/dist/npcap-1.78.exe
        arguments:
        - /S
    
    - name: Installing Suricata
      ansible.windows.win_package:
        path: https://www.openinfosecfoundation.org/download/windows/Suricata-7.0.2-1-64bit.msi
    
    tags:
    - Setup

  - name: Configure suricata.yaml
    template:
      src: /etc/ansible/templates/windows-suricata.j2
      dest: 'C:\Program Files\Suricata\suricata.yaml'
    tags:
    - Configuration

  - name: Download Default ET Rules
    ansible.windows.win_get_url:
      url: https://rules.emergingthreats.net/open/suricata/emerging-all.rules
      dest: 'C:\Program Files\Suricata\rules\emerging-all.rules'
    tags:
    - Configuration

  - name: Run Suricata
    ansible.windows.win_command: .\Suricata.exe -c suricata.yaml -i  {{ ansible_default_ipv4.address }} --service-install
    args:
      chdir: 'C:\Program Files\Suricata'
    tags:
    - Startup


- name: Install Suricata on Linux
  hosts: linux_hosts,manager
  become: yes
  tags:
  - Linux
  tasks:
  - name: Install Suricata on Debian
    block:
    - name: Adding Repository on Debian 
      ansible.builtin.apt_repository:
        repo: ppa:oisf/suricata-stable
        state: present
  
    - name: Installing Suricata on Debian
      ansible.builtin.apt:
        name:
        - suricata
        state: present

    when: ansible_os_family == 'Debian'
    tags:
    - Setup
    - Debian

  - name: Install Suricata on RedHat/Centos/Fedora
    block:
    - name: Installing Dependencies on RedHat/Centos/Fedora
      ansible.builtin.dnf:
        name:
        - epel-release
        - yum-plugin-copr
        state: present

    - name: Adding Repository on RedHat/Centos/Fedora
      community.general.copr: 
        name: '@oisf/suricata-7.0'
        state: enabled
    
    - name: Installing Suricata on RedHat/Centos/Fedora
      ansible.builtin.dnf:
        name: suricata
        state: present
    
    when: (( ansible_distribution == 'RedHat' or distribution == 'CentOS') and distribution_major_version | int >= 8 ) 
          or
          ( ansible_distribution == 'Fedora' and ansible_distribution_major_version | int >= 22 )
    tags:
    - Setup
    - RedHat
    - Fedora
    - Centos

  - name: Setup on Old RedHat/Centos/Fedora
    block:
    - name: Installing Dependencies on RedHat/Centos/Fedora
      ansible.builtin.yum:
        name:
        - epel-release
        - yum-plugin-copr
        state: present
    
    - name: Adding Repository on RedHat/Centos/Fedora
      community.general.copr: 
        name: '@oisf/suricata-7.0'
        state: enabled

    - name: Installing Suricata on RedHat/Centos/Fedora
      ansible.builtin.yum:
        name: suricata
        state: present

    when: ( ansible_os_family == 'RedHat' and ansible_distribution_major_version | int <= 7 ) 
          or 
          ( ansible_distribution == 'Fedora' and ansible_distribution_major_version | int <= 21 )
    tags:
      - Setup
      - RedHat
      - Fedora
      - Centos
     
  - name: Install Suricata on Suse
    block:
    - name: Installing Dependencies on Suse
      community.general.zypper:
        name:
        - wget 
        - tar 
        - gcc
        - pkg-config 
        - pcre-devel 
        - libyaml-devel
        - libpcap-devel 
        - zlib-devel 
        - file-devel
        - make
        - libnetfilter_queue-devel
        - libjansson-devel 
        - mozilla-nss-devel
        - libcap-ng-devel 
        - lua5*-devel
        state: present
    
    - name: Download and unzip source files
      ansible.builtin.unarchive:
        remote_src: true
        src: https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz
        dest: /home/{{ ansible_ssh_user }}/suricata-4.0.5

    - name: Running ./configure
      become: yes
      vars:
        inputs: "--prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-nfqueue --enable-lua"
      ansible.builtin.command: 
        cmd: ./configure {{ inputs }}
        chdir: /home/{{ ansible_ssh_user }}/suricata-4.0.5
      environment:
        CPPFLAGS: "-I/usr/include/libnetfilter_queue/ -I/usr/include/libnfnetlink/"

    - name: Running make install-full
      become: yes
      ansible.builtin.shell: make && make install-full && ld-config

    when: ansible_os_family == 'Suse'
    tags:
    - Setup
    - Suse
      
  - name: Setup on ArchLinux
    become: yes
    communtiy.general.pacman:
      name: suricata
      update_cache: true
    when: ansible_os_family == 'Archlinux'
    tags:
    - Setup
    - ArchLinux

  - name: Setup on Alpine
    become: yes
    community.general.apk:
      name: suricata
      update_cache: true
    when: ansible_os_family == 'Alpine'
    tags:
    - Setup
    - Alpine

  - name: Configuring on All
    become: yes
    block:
    - name: Configuring suricata.yaml
      template:
        src: /etc/ansible/templates/linux-suricata.j2
        dest: /etc/suricata/suricata.yaml
    
    - name: Restarting Suricata
      ansible.builtin.service:
        name: suricata
        state: restarted

    - name: Running suricata-update
      ansible.builtin.command: suricata-update

    tags:
    - Configuration
