# Main playbook to run all roles

- name: Add Users
  hosts: all
  roles:
    - create
  tags: 
    - "Create Users"

- name: Change Passwords
  hosts: all
  roles:
    - change_passwords
  tags: 
    - "Change Passwords"

- name: Remove Users
  hosts: all
  roles:
    - remove
  tags: 
    - "Remove Users"
