- name: Installing Dependencies on RedHat/Centos/Fedora
  ansible.builtin.dnf:
    name:
    - epel-release
    - yum-plugin-copr
    state: present

- name: Adding Repository on RedHat/Centos/Fedora
  community.general.copr:
    name: {{ redhat_package }}
    state: enabled

- name: Installing Suricata on RedHat/Centos/Fedora
  ansible.builtin.dnf:
    name: suricata
    state: present
