# Variables for RedHat Setup

redhat_package: '@oisf/suricata-7.0'


# Variables for SUSE Setup

suse_config_inputs: "--prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-nfqueue --enable-lua"
suse_suricata_dir: {{ ansible_home }}suricata-6.0.15
suse_suricata_download: https://www.openinfosecfoundation.org/download/suricata-6.0.15.tar.gz
suse_dependencies: 
  - wget
  - tar
  - gcc
  - pkg-config
  - pcre-devel
  - libyaml-devel
  - libpcap-devel
  - zlib-devel
  - file-devel
  - make
  - libnetfilter_queue-devel
  - libjansson-devel
  - mozilla-nss-devel
  - libcap-ng-devel
  - lua5*-devel
