# Install Suricata on All Linux Distros

- name: Setup on Debian
  import_tasks: debian.yaml
  when: ansible_os_family == 'Debian'
  tags:
  - Setup
  - Debian

- name: Setup on RedHat/Centos/Fedora
  import_tasks: redhat.yaml
  when: (( ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version | int >= 8 )
        or
        ( ansible_distribution == 'Fedora' and ansible_distribution_major_version | int >= 22 )
  tags:
  - Setup
  - RedHat
  - Fedora
  - Centos

- name: Setup on old RedHat/Centos/Fedora 
  import_tasks: old_redhat.yaml
  when: ( ansible_os_family == 'RedHat' and ansible_distribution_major_version | int <= 7 )
        or
        ( ansible_distribution == 'Fedora' and ansible_distribution_major_version | int <= 21 )
  tags:
    - Setup
    - RedHat
    - Fedora
    - Centos

- name: Setup on Suse
  block:
  - name: Refresh and update all packages on Suse
    community.general.zypper:
      name: '*'
      update_cache: true
      state: latest

  - name: install Dependencies on Suse
    community.general.zypper:
      name: "{{ suse_dependencies }}"
      state: present
      update_cache: true

  - name: Try Installing with Package Manager
    import_tasks: suse_package.yaml
  when: ansible_os_family == 'Suse'
  
  rescue:
  - name: Install Using Source Files
    import_tasks: suse_source.yaml
  when: ansible_os_family == 'Suse'
  tags:
  - Setup
  - Suse

- name: Install Suricata using Package Manager
  ansible.builtin.package:
    name: suricata
    state: present
  when: ansible_os_family != "Suse"
