- name: Installing Dependencies on RedHat/Centos/Fedora
  ansible.builtin.yum:
    name:
    - epel-release
    - yum-plugin-copr
    state: present
    update_cache: true

- name: Adding Repository on RedHat/Centos/Fedora
  become: yes
  ansible.builtin.command:
    cmd: yum -y copr enable {{ redhat_package }}

- name: Installing Suricata on RedHat/Centos/Fedora
  ansible.builtin.yum:
    name: suricata
    state: present
    update_cache: true
