# Installs Suricata's Windows Dependencies

- name: Installing npcap
  ansible.windows.win_package:
  url: {{ npcap_download }} 
    arguments:
    - /S
    
- name: Installing Suricata
  ansible.windows.win_package:
    path: {{ suricata_download }} 
