# Install Suricata on Both Windows and Linux Systems

- name: Install Suricata on Windows
  hosts: windows_hosts
  become: yes
  become_method: runas
  become_user: Administrator
  tags:
  - Windows
  roles:
    - windows

- name: Install Suricata on Linux
  hosts: linux_hosts
  become: yes
  tags:
  - Linux
  roles:
    - linux_setup
    - role: linux_configure
      tags: Configuration
