- name: Configure suricata.yaml
  template:
    src: windows-suricata.j2
    dest: {{ config_path }} 

- name: Download Default ET Rules
  ansible.windows.win_get_url:
    url: https://rules.emergingthreats.net/open/suricata/emerging-all.rules
    dest: {{ rules_path }} 

- name: Create Suricata Service
  ansible.windows.win_command: .\Suricata.exe -c suricata.yaml -i  {{ ansible_default_ipv4.address }} --service-install
  args:
    chdir: {{ suricata_dir }} 
  tags: Startup

- name: Start Suricata
  ansible.windows.win_service:
    name: Suricata
    start_mode: auto
    state: restarted
    failure_actions:
      type: restart
      delay_ms: 100
  tags: Startup
